{% set name = "numbers-parser" %}
{% set version = "2.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numbers-parser-{{ version }}.tar.gz
  sha256: ecaa17f0da6640158dfb7ed2495d9f3f8287ddc0a3bd725bde4c0207478749aa

build:
  number: 0
  noarch: python
  entry_points:
    - cat-numbers=numbers_parser._cat_numbers:main
    - unpack-numbers=numbers_parser._unpack_numbers:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - protobuf
    - pytest
    - python >=3.6
    - python-snappy
    - pyyaml
    - roman

test:
  source_files:
    - tests
  imports:
    - numbers_parser
    - numbers_parser.generated
  commands:
    - pip check
    - cat-numbers --help
    - unpack-numbers --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/masaccio/numbers-parser
  summary: Package to read data from Apple Numbers spreadsheets
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
