{% set name = "numbers-parser" %}
{% set version = "4.10.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c7f21683238def09b289d76d90c22c301174a3d6aa9fddc74e2df3ebc75d4442

build:
  number: 0
  noarch: python
  entry_points:
    - cat-numbers=numbers_parser._cat_numbers:main
    - unpack-numbers=numbers_parser._unpack_numbers:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9,<4.0
    - setuptools <70.0.0,>=69.0.3

  run:
    - python >=3.9,<4.0
    - compact-json >=1.1.3,<2.0.0
    - pendulum <4.0,>=3.0
    - protobuf
    - python-snappy <0.8,>=0.7
    - regex >2024.0
    - roman >=4.0
    - setuptools <70.0.0,>=69.0.3
    - sigfig >=1.3.2,<2.0.0
    - importlib-resources >=6.1.1,<7.0.0
    - enum_tools >=0.11.0,<0.12.0

test:
  imports:
    - numbers_parser
    - numbers_parser.generated
  commands:
    - pip check
    - cat-numbers --help
    - unpack-numbers --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/numbers-parser
  summary: Package to read data from Apple Numbers spreadsheets
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
