{% set name = "numbers-parser" %}
{% set version = "4.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c93cf9782e73864aa2aa30673a2620a347ebead9e32c39a445d184b73d8a4482

build:
  number: 0
  noarch: python
  entry_points:
    - cat-numbers=numbers_parser._cat_numbers:main
    - unpack-numbers=numbers_parser._unpack_numbers:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
    - setuptools <70.0.0,>=69.0.3

  run:
    - compact-json >=1.1.3,<2.0.0
    - pendulum <4.0,>=3.0
    - protobuf >=4.21.1,<5.0.0
    - python >=3.8,<4.0
    - python-snappy >=0.6.1,<0.7.0
    - regex >=2022.9.13,<2023.0.0
    - roman >=3.3.0,<4.0.0
    - setuptools <70.0.0,>=69.0.3
    - sigfig >=1.3.2,<2.0.0

test:
  imports:
    - numbers_parser
    - numbers_parser.generated
  commands:
    - pip check
    - cat-numbers --help
    - unpack-numbers --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/numbers-parser
  summary: Package to read data from Apple Numbers spreadsheets
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
