{% set name = "numbers-parser" %}
{% set version = "2.3.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numbers-parser-{{ version }}.tar.gz
  sha256: 07e3e1dda2d81a11a9d7e5c765f5bb17defa1e7ac418cb6df0af20f052ccf06a

build:
  number: 0
  noarch: python
  entry_points:
    - cat-numbers=numbers_parser._cat_numbers:main
    - unpack-numbers=numbers_parser._unpack_numbers:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - protobuf
    - python >=3.6
    - python-snappy
    - roman

test:
  imports:
    - numbers_parser
    - numbers_parser.generated
  commands:
    - pip check
    - cat-numbers --help
    - unpack-numbers --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/numbers-parser
  summary: Package to read data from Apple Numbers spreadsheets
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
