{% set name = "numbers-parser" %}
{% set version = "3.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numbers-parser-{{ version }}.tar.gz
  sha256: 6a4f191974c6781cccf35d2813f13ba0bd909eb3c854b84079cdba027048bdfb

build:
  number: 0
  noarch: python
  entry_points:
    - cat-numbers=numbers_parser._cat_numbers:main
    - unpack-numbers=numbers_parser._unpack_numbers:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - compact-json
    - protobuf >=3.20.1
    - python >=3.8
    - python-snappy
    - regex
    - roman

test:
  imports:
    - numbers_parser
    - numbers_parser.generated
  commands:
    - pip check
    - cat-numbers --help
    - unpack-numbers --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/numbers-parser
  summary: Package to read data from Apple Numbers spreadsheets
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
