{% set name = "numbers-parser" %}
{% set version = "4.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1c18c2bdb850f9321c9c4015952b3a74e803965446bd2bb0a8860bfde0ad3556

build:
  number: 0
  noarch: python
  entry_points:
    - cat-numbers=numbers_parser._cat_numbers:main
    - unpack-numbers=numbers_parser._unpack_numbers:main
    - csv2numbers=numbers_parser._csv2numbers:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=61.0
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - compact-json >=1.1.3,<2.0.0
    - protobuf <6.0,>=4.0
    - python-snappy >=0.7,<1.0
    - sigfig >=1.3.3,<2.0.0
    - setuptools >=70.0.0
    - importlib-resources >=6.1
    - enum_tools >=0.11
    - python-dateutil >=2.9.0.post0,<3.0.0.0

test:
  imports:
    - numbers_parser
  commands:
    - pip check
    - cat-numbers --help
    - unpack-numbers --help
    - csv2numbers --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/masaccio/numbers-parser
  summary: Package to read data from Apple Numbers spreadsheets
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
