{% set name = "numbers-parser" %}
{% set version = "4.14.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 57f1a136c7ec036bd6b664fc9ce9a88268ed31911ba6944c0c600f4e68b37eae

build:
  number: 0
  noarch: python
  entry_points:
    - cat-numbers=numbers_parser._cat_numbers:main
    - unpack-numbers=numbers_parser._unpack_numbers:main
    - csv2numbers=numbers_parser._csv2numbers:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9,<4.0

  run:
    - python >=3.9,<4.0
    - compact-json >=1.1.3,<2.0.0
    - pendulum >=3.0.0,<4.0.0
    - protobuf
    - python-snappy >=0.7.0,<0.8.0
    - regex >2024.0
    - roman >=4.0
    - setuptools >=69.0.3
    - sigfig >=1.3.2,<2.0.0
    - setuptools >=69.0.3
    - importlib-resources >=6.1
    - enum_tools >=0.11
    - colorama >=0.4.6,<0.5.0

test:
  imports:
    - numbers_parser
  commands:
    - pip check
    - cat-numbers --help
    - unpack-numbers --help
    - csv2numbers --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/numbers-parser
  summary: Package to read data from Apple Numbers spreadsheets
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
